{
  "abstract" : [
    {
      "text" : "Notifies your app when the user receives an award",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(on:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(pl)POLPollingDelegate(im)pollingOnReward:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "polling"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "externalParam",
        "text" : "on"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)POLPolling",
        "text" : "Polling"
      },
      {
        "kind" : "text",
        "text" : "."
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)POLReward",
        "text" : "Reward"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "pollingOnReward:"
      }
    ],
    "required" : true,
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "polling(on:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "optional"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "polling"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "on"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "reward"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)POLPolling",
              "text" : "Polling"
            },
            {
              "kind" : "text",
              "text" : "."
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)POLReward",
              "text" : "Reward"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "An ",
                  "type" : "text"
                },
                {
                  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
                  "isActive" : true,
                  "type" : "reference"
                },
                {
                  "text" : " encapsulating the reward",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "reward"
        }
      ]
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Called after a user completes a survey with an associated award.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/pollingdelegate\/polling(on:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/pollingdelegate\/polling(on:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/Reward": {
  "abstract" : [
    {
      "text" : "An object representing a reward",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.Reward",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/reward"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate": {
  "abstract" : [
    {
      "text" : "A protocol that defines methods the SDK can call to provide",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "information to your app",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "PollingDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "PollingDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "PollingDelegate",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate/polling(on:)": {
  "abstract" : [
    {
      "text" : "Notifies your app when the user receives an award",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "polling"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "on"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLReward",
      "text" : "Reward"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(on:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "pollingOnReward:"
    }
  ],
  "required" : true,
  "role" : "symbol",
  "title" : "polling(on:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate\/polling(on:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "pollingOnReward:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnReward:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "- ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:v",
                  "text" : "void"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "pollingOnReward:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)POLReward",
                  "text" : "POLReward"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "reward"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/1",
        "value" : {
          "kind" : "parameters",
          "parameters" : [
            {
              "content" : [
                {
                  "inlineContent" : [
                    {
                      "text" : "An ",
                      "type" : "text"
                    },
                    {
                      "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
                      "isActive" : true,
                      "type" : "reference"
                    },
                    {
                      "text" : " encapsulating the reward",
                      "type" : "text"
                    }
                  ],
                  "type" : "paragraph"
                }
              ],
              "name" : "reward"
            }
          ]
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/title",
        "value" : "POLReward"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/title",
        "value" : "POLPollingDelegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(on:)\/title",
        "value" : "pollingOnReward:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(on:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnReward:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}