{
  "abstract" : [
    {
      "text" : "Show a specific survey",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showSurvey(_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(cs)POLPolling(im)showSurvey:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "showSurvey"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SS",
        "text" : "String"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "showSurvey:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "showSurvey(_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "showSurvey"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "surveyUuid"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SS",
              "text" : "String"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "The UUID of the survey to show",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "surveyUuid"
        }
      ]
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Show a specific survey identified by its UUID. Survey UUIDs are",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "available on the ",
              "type" : "text"
            },
            {
              "identifier" : "Polling.com",
              "isActive" : true,
              "type" : "reference"
            },
            {
              "text" : " dashboard.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling\/showsurvey(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling\/showsurvey(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"Polling.com": {
  "identifier" : "Polling.com",
  "title" : "Polling.com",
  "titleInlineContent" : [
    {
      "text" : "Polling.com",
      "type" : "text"
    }
  ],
  "type" : "link",
  "url" : "Polling.com"
},
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/showSurvey(_:)": {
  "abstract" : [
    {
      "text" : "Show a specific survey",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "showSurvey"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showSurvey(_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "showSurvey:"
    }
  ],
  "role" : "symbol",
  "title" : "showSurvey(_:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/showsurvey(_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "showSurvey:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "showSurvey:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "- ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:v",
                  "text" : "void"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "showSurvey:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSString",
                  "text" : "NSString"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "surveyUuid"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/1",
        "value" : {
          "kind" : "parameters",
          "parameters" : [
            {
              "content" : [
                {
                  "inlineContent" : [
                    {
                      "text" : "The UUID of the survey to show",
                      "type" : "text"
                    }
                  ],
                  "type" : "paragraph"
                }
              ],
              "name" : "surveyUuid"
            }
          ]
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showSurvey(_:)\/title",
        "value" : "showSurvey:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showSurvey(_:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "showSurvey:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}