{
  "abstract" : [
    {
      "text" : "An object representing a survey",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling"
      ],
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey"
  },
  "kind" : "symbol",
  "metadata" : {
    "extendedModule" : "Polling",
    "externalID" : "c:objc(cs)POLSurvey",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "class"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "Survey"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "Survey"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Class",
    "symbolKind" : "class",
    "title" : "Polling.Survey"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "class"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "Survey"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "A model object that encapsulates information specific to a survey.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/objc(cs)NSObject"
      ],
      "kind" : "relationships",
      "title" : "Inherits From",
      "type" : "inheritsFrom"
    },
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/objc(pl)NSObject",
        "doc:\/\/com.polling.polling\/s7CVarArgP",
        "doc:\/\/com.polling.polling\/s28CustomDebugStringConvertibleP",
        "doc:\/\/com.polling.polling\/s23CustomStringConvertibleP",
        "doc:\/\/com.polling.polling\/SQ",
        "doc:\/\/com.polling.polling\/SH"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Instance-Properties",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isAvailable",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isCompleted",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isStarted",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/name",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/questionCount",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/reward",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/uuid"
      ],
      "title" : "Instance Properties"
    },
    {
      "anchor" : "Instance-Methods",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isEqual(to:)"
      ],
      "title" : "Instance Methods"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling\/survey"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling\/survey"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/SH": {
  "identifier" : "doc:\/\/com.polling.polling\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/SQ": {
  "identifier" : "doc:\/\/com.polling.polling\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey": {
  "abstract" : [
    {
      "text" : "An object representing a survey",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Survey"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Survey"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.Survey",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/isAvailable": {
  "abstract" : [
    {
      "code" : "YES",
      "type" : "codeVoice"
    },
    {
      "text" : " if the survey is available",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isAvailable"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isAvailable",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "available"
    }
  ],
  "role" : "symbol",
  "title" : "isAvailable",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/isavailable"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/isCompleted": {
  "abstract" : [
    {
      "code" : "YES",
      "type" : "codeVoice"
    },
    {
      "text" : " when the survey is completed",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isCompleted"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isCompleted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "completed"
    }
  ],
  "role" : "symbol",
  "title" : "isCompleted",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/iscompleted"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/isEqual(to:)": {
  "abstract" : [
    {
      "text" : "Indicates whether a given survey is equal to the receiver",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isEqual"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "to"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLSurvey",
      "text" : "Survey"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isEqual(to:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "isEqualToSurvey:"
    }
  ],
  "role" : "symbol",
  "title" : "isEqual(to:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/isequal(to:)"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/isStarted": {
  "abstract" : [
    {
      "code" : "YES",
      "type" : "codeVoice"
    },
    {
      "text" : " if the survey has been opened but not completed",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isStarted"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isStarted",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "started"
    }
  ],
  "role" : "symbol",
  "title" : "isStarted",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/isstarted"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/name": {
  "abstract" : [
    {
      "text" : "Name of the survey",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "name"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/name",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "name"
    }
  ],
  "role" : "symbol",
  "title" : "name",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/name"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/questionCount": {
  "abstract" : [
    {
      "text" : "Number of questions the survey contains",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "questionCount"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Su",
      "text" : "UInt"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/questionCount",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "questionCount"
    }
  ],
  "role" : "symbol",
  "title" : "questionCount",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/questioncount"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/reward": {
  "abstract" : [
    {
      "text" : "Reward associated with the survey or ",
      "type" : "text"
    },
    {
      "code" : "nil",
      "type" : "codeVoice"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "reward"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLReward",
      "text" : "Reward"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/reward",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "reward"
    }
  ],
  "role" : "symbol",
  "title" : "reward",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/reward"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey/uuid": {
  "abstract" : [
    {
      "text" : "The survey’s UUID",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "uuid"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/uuid",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "UUID"
    }
  ],
  "role" : "symbol",
  "title" : "uuid",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey\/uuid"
},
"doc://com.polling.polling/objc(cs)NSObject": {
  "identifier" : "doc:\/\/com.polling.polling\/objc(cs)NSObject",
  "title" : "NSObject",
  "type" : "unresolvable"
},
"doc://com.polling.polling/objc(pl)NSObject": {
  "identifier" : "doc:\/\/com.polling.polling\/objc(pl)NSObject",
  "title" : "ObjectiveC.NSObjectProtocol",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s23CustomStringConvertibleP": {
  "identifier" : "doc:\/\/com.polling.polling\/s23CustomStringConvertibleP",
  "title" : "Swift.CustomStringConvertible",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s28CustomDebugStringConvertibleP": {
  "identifier" : "doc:\/\/com.polling.polling\/s28CustomDebugStringConvertibleP",
  "title" : "Swift.CustomDebugStringConvertible",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s7CVarArgP": {
  "identifier" : "doc:\/\/com.polling.polling\/s7CVarArgP",
  "title" : "Swift.CVarArg",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "POLSurvey"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Instance-Properties",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isAvailable",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isCompleted",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isStarted",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/name",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/questionCount",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/reward",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/uuid"
            ],
            "title" : "Instance Properties"
          },
          {
            "anchor" : "Instance-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey\/isEqual(to:)"
            ],
            "title" : "Instance Methods"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/com.polling.polling\/objc(cs)NSObject"
            ],
            "kind" : "relationships",
            "title" : "Inherits From",
            "type" : "inheritsFrom"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@interface"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "POLSurvey"
                },
                {
                  "kind" : "text",
                  "text" : " : "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSObject",
                  "text" : "NSObject"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/title",
        "value" : "POLSurvey"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isAvailable\/title",
        "value" : "available"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isAvailable\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "available"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isCompleted\/title",
        "value" : "completed"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isCompleted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "completed"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isEqual(to:)\/title",
        "value" : "isEqualToSurvey:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isEqual(to:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "isEqualToSurvey:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isStarted\/title",
        "value" : "started"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1isStarted\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "started"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1name\/title",
        "value" : "name"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1name\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "name"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1questionCount\/title",
        "value" : "questionCount"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1questionCount\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "questionCount"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1reward\/title",
        "value" : "reward"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1reward\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "reward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1uuid\/title",
        "value" : "UUID"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey~1uuid\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "UUID"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}