{
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/viewType-swift.property"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(cs)POLPolling(py)viewType",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "var"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "viewType"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)POLPolling",
        "text" : "Polling"
      },
      {
        "kind" : "text",
        "text" : "."
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@POLViewType",
        "text" : "ViewType"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "viewType"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Property",
    "symbolKind" : "property",
    "title" : "viewType"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "var"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "viewType"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)POLPolling",
              "text" : "Polling"
            },
            {
              "kind" : "text",
              "text" : "."
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@POLViewType",
              "text" : "ViewType"
            },
            {
              "kind" : "text",
              "text" : " { "
            },
            {
              "kind" : "keyword",
              "text" : "get"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "set"
            },
            {
              "kind" : "text",
              "text" : " }"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Set this property before using ",
              "type" : "text"
            },
            {
              "code" : "showSurvey:",
              "type" : "codeVoice"
            },
            {
              "text" : " or ",
              "type" : "text"
            },
            {
              "code" : "showEmbedView",
              "type" : "codeVoice"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "to display the survey or embed using a view style.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling\/viewtype-swift.property"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling\/viewtype-swift.property"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum": {
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum"
},
"doc://com.polling.polling/documentation/Polling/Polling/viewType-swift.property": {
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "viewType"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@POLViewType",
      "text" : "ViewType"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/viewType-swift.property",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "viewType"
    }
  ],
  "role" : "symbol",
  "title" : "viewType",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.property"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "viewType"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "viewType"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@property"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@E@POLViewType",
                  "text" : "POLViewType"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "viewType"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/title",
        "value" : "POLViewType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1viewType-swift.property\/title",
        "value" : "viewType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1viewType-swift.property\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "viewType"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}