{
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling"
      ],
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum"
  },
  "kind" : "symbol",
  "metadata" : {
    "extendedModule" : "Polling",
    "externalID" : "c:@E@POLViewType",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "enum"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "ViewType"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "ViewType"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Enumeration",
    "symbolKind" : "enum",
    "title" : "Polling.ViewType"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "enum"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "ViewType"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/s15BitwiseCopyableP",
        "doc:\/\/com.polling.polling\/SQ",
        "doc:\/\/com.polling.polling\/SH",
        "doc:\/\/com.polling.polling\/SY",
        "doc:\/\/com.polling.polling\/s8SendableP"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Enumeration-Cases",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/bottom",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/dialog",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/none"
      ],
      "title" : "Enumeration Cases"
    },
    {
      "anchor" : "Initializers",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/init(rawValue:)"
      ],
      "title" : "Initializers"
    },
    {
      "anchor" : "Default-Implementations",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/Equatable-Implementations",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/RawRepresentable-Implementations"
      ],
      "title" : "Default Implementations"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling\/viewtype-swift.enum"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling\/viewtype-swift.enum"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/SH": {
  "identifier" : "doc:\/\/com.polling.polling\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/SQ": {
  "identifier" : "doc:\/\/com.polling.polling\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/SY": {
  "identifier" : "doc:\/\/com.polling.polling\/SY",
  "title" : "Swift.RawRepresentable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum": {
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/Equatable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/Equatable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "Equatable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/equatable-implementations"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/RawRepresentable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/RawRepresentable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "RawRepresentable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/rawrepresentable-implementations"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/bottom": {
  "abstract" : [
    {
      "text" : "Display survey in a sheet that slides up from the bottom over",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "existing app content.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "bottom"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/bottom",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "POLViewTypeBottom"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType.bottom",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/bottom"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/dialog": {
  "abstract" : [
    {
      "text" : "Display survey in view that is centered over existing app",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "content.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "dialog"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/dialog",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "POLViewTypeDialog"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType.dialog",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/dialog"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/init(rawValue:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "?("
    },
    {
      "kind" : "externalParam",
      "text" : "rawValue"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Si",
      "text" : "Int"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/init(rawValue:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(rawValue:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/init(rawvalue:)"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum/none": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "none"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/none",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "POLViewTypeNone"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType.none",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum\/none"
},
"doc://com.polling.polling/s15BitwiseCopyableP": {
  "identifier" : "doc:\/\/com.polling.polling\/s15BitwiseCopyableP",
  "title" : "Swift.BitwiseCopyable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s8SendableP": {
  "identifier" : "doc:\/\/com.polling.polling\/s8SendableP",
  "title" : "Swift.Sendable",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "POLViewType"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "enum"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Enumeration-Cases",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/bottom",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/dialog",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum\/none"
            ],
            "title" : "Enumeration Cases"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "POLViewType"
                },
                {
                  "kind" : "text",
                  "text" : ": "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@NSInteger",
                  "text" : "NSInteger"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/title",
        "value" : "POLViewType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1bottom\/title",
        "value" : "POLViewTypeBottom"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1bottom\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewTypeBottom"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1dialog\/title",
        "value" : "POLViewTypeDialog"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1dialog\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewTypeDialog"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1none\/title",
        "value" : "POLViewTypeNone"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum~1none\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewTypeNone"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}