{
  "abstract" : [
    {
      "text" : "The reward amount",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward"
      ],
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward\/amount"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(cs)POLReward(py)amount",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "var"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "amount"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SS",
        "text" : "String"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "amount"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Property",
    "symbolKind" : "property",
    "title" : "amount"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "var"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "amount"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SS",
              "text" : "String"
            },
            {
              "kind" : "text",
              "text" : " { "
            },
            {
              "kind" : "keyword",
              "text" : "get"
            },
            {
              "kind" : "text",
              "text" : " }"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling\/reward\/amount"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling\/reward\/amount"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/Reward": {
  "abstract" : [
    {
      "text" : "An object representing a reward",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.Reward",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/reward"
},
"doc://com.polling.polling/documentation/Polling/Polling/Reward/amount": {
  "abstract" : [
    {
      "text" : "The reward amount",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "amount"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward\/amount",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "amount"
    }
  ],
  "role" : "symbol",
  "title" : "amount",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/reward\/amount"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "amount"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "amount"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@property"
                },
                {
                  "kind" : "text",
                  "text" : " ("
                },
                {
                  "kind" : "keyword",
                  "text" : "readonly"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSString",
                  "text" : "NSString"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "identifier",
                  "text" : "amount"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/title",
        "value" : "POLReward"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward~1amount\/title",
        "value" : "amount"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward~1amount\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "amount"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}