{
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(cs)POLPolling",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "class"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "Polling"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "Polling"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Class",
    "symbolKind" : "class",
    "title" : "Polling"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "class"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "Polling"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Configure the SDK and to access features like sending log events",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "and displaying surveys.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/objc(cs)NSObject"
      ],
      "kind" : "relationships",
      "title" : "Inherits From",
      "type" : "inheritsFrom"
    },
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/objc(pl)NSObject",
        "doc:\/\/com.polling.polling\/s7CVarArgP",
        "doc:\/\/com.polling.polling\/s28CustomDebugStringConvertibleP",
        "doc:\/\/com.polling.polling\/s23CustomStringConvertibleP",
        "doc:\/\/com.polling.polling\/SQ",
        "doc:\/\/com.polling.polling\/SH"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Classes",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey"
      ],
      "title" : "Classes"
    },
    {
      "anchor" : "Initializers",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/init()"
      ],
      "title" : "Initializers"
    },
    {
      "anchor" : "Instance-Properties",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/apiKey",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/customerID",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/delegate",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/disableCheckingForAvailableSurveys",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/viewType-swift.property"
      ],
      "title" : "Instance Properties"
    },
    {
      "anchor" : "Instance-Methods",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logEvent(_:value:)",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logPurchase(_:)",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logSession()",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showEmbedView()",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showSurvey(_:)"
      ],
      "title" : "Instance Methods"
    },
    {
      "anchor" : "Enumerations",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum"
      ],
      "title" : "Enumerations"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/polling"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/polling"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/SH": {
  "identifier" : "doc:\/\/com.polling.polling\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/SQ": {
  "identifier" : "doc:\/\/com.polling.polling\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/Reward": {
  "abstract" : [
    {
      "text" : "An object representing a reward",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Reward",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Reward"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.Reward",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/reward"
},
"doc://com.polling.polling/documentation/Polling/Polling/Survey": {
  "abstract" : [
    {
      "text" : "An object representing a survey",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Survey"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/Survey",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Survey"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.Survey",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/survey"
},
"doc://com.polling.polling/documentation/Polling/Polling/ViewType-swift.enum": {
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/ViewType-swift.enum",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ViewType"
    }
  ],
  "role" : "symbol",
  "title" : "Polling.ViewType",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.enum"
},
"doc://com.polling.polling/documentation/Polling/Polling/apiKey": {
  "abstract" : [
    {
      "text" : "An API Key",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "apiKey"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/apiKey",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "apiKey"
    }
  ],
  "role" : "symbol",
  "title" : "apiKey",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/apikey"
},
"doc://com.polling.polling/documentation/Polling/Polling/customerID": {
  "abstract" : [
    {
      "text" : "An string that uniquely identifies your customer",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "customerID"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/customerID",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "customerID"
    }
  ],
  "role" : "symbol",
  "title" : "customerID",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/customerid"
},
"doc://com.polling.polling/documentation/Polling/Polling/delegate": {
  "abstract" : [
    {
      "text" : "Delegate that handles callbacks from the SDK",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "delegate"
    },
    {
      "kind" : "text",
      "text" : ": (any "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(pl)POLPollingDelegate",
      "text" : "PollingDelegate"
    },
    {
      "kind" : "text",
      "text" : ")?"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/delegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "delegate"
    }
  ],
  "role" : "symbol",
  "title" : "delegate",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/delegate"
},
"doc://com.polling.polling/documentation/Polling/Polling/disableCheckingForAvailableSurveys": {
  "abstract" : [
    {
      "text" : "Disable survey availability checks",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "disableCheckingForAvailableSurveys"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/disableCheckingForAvailableSurveys",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "disableCheckingForAvailableSurveys"
    }
  ],
  "role" : "symbol",
  "title" : "disableCheckingForAvailableSurveys",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/disablecheckingforavailablesurveys"
},
"doc://com.polling.polling/documentation/Polling/Polling/init()": {
  "abstract" : [
    {
      "text" : "Returns the ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " singleton object.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "convenience"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/init()",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "polling"
    }
  ],
  "role" : "symbol",
  "title" : "init()",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/init()"
},
"doc://com.polling.polling/documentation/Polling/Polling/logEvent(_:value:)": {
  "abstract" : [
    {
      "text" : "Send and log events",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "logEvent"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "externalParam",
      "text" : "value"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logEvent(_:value:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "logEvent:value:"
    }
  ],
  "role" : "symbol",
  "title" : "logEvent(_:value:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/logevent(_:value:)"
},
"doc://com.polling.polling/documentation/Polling/Polling/logPurchase(_:)": {
  "abstract" : [
    {
      "text" : "Log a purchase",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "logPurchase"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5Int32V",
      "text" : "Int32"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logPurchase(_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "logPurchase:"
    }
  ],
  "role" : "symbol",
  "title" : "logPurchase(_:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/logpurchase(_:)"
},
"doc://com.polling.polling/documentation/Polling/Polling/logSession()": {
  "abstract" : [
    {
      "text" : "Log user session",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "logSession"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logSession()",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "logSession"
    }
  ],
  "role" : "symbol",
  "title" : "logSession()",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/logsession()"
},
"doc://com.polling.polling/documentation/Polling/Polling/showEmbedView()": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "showEmbedView"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showEmbedView()",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "showEmbedView"
    }
  ],
  "role" : "symbol",
  "title" : "showEmbedView()",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/showembedview()"
},
"doc://com.polling.polling/documentation/Polling/Polling/showSurvey(_:)": {
  "abstract" : [
    {
      "text" : "Show a specific survey",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "showSurvey"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showSurvey(_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "showSurvey:"
    }
  ],
  "role" : "symbol",
  "title" : "showSurvey(_:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/showsurvey(_:)"
},
"doc://com.polling.polling/documentation/Polling/Polling/viewType-swift.property": {
  "abstract" : [
    {
      "text" : "Survey view style",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "viewType"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@POLViewType",
      "text" : "ViewType"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/viewType-swift.property",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "viewType"
    }
  ],
  "role" : "symbol",
  "title" : "viewType",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/viewtype-swift.property"
},
"doc://com.polling.polling/objc(cs)NSObject": {
  "identifier" : "doc:\/\/com.polling.polling\/objc(cs)NSObject",
  "title" : "NSObject",
  "type" : "unresolvable"
},
"doc://com.polling.polling/objc(pl)NSObject": {
  "identifier" : "doc:\/\/com.polling.polling\/objc(pl)NSObject",
  "title" : "ObjectiveC.NSObjectProtocol",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s23CustomStringConvertibleP": {
  "identifier" : "doc:\/\/com.polling.polling\/s23CustomStringConvertibleP",
  "title" : "Swift.CustomStringConvertible",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s28CustomDebugStringConvertibleP": {
  "identifier" : "doc:\/\/com.polling.polling\/s28CustomDebugStringConvertibleP",
  "title" : "Swift.CustomDebugStringConvertible",
  "type" : "unresolvable"
},
"doc://com.polling.polling/s7CVarArgP": {
  "identifier" : "doc:\/\/com.polling.polling\/s7CVarArgP",
  "title" : "Swift.CVarArg",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Instance-Properties",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/apiKey",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/customerID",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/delegate",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/disableCheckingForAvailableSurveys",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/viewType-swift.property"
            ],
            "title" : "Instance Properties"
          },
          {
            "anchor" : "Instance-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logEvent(_:value:)",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logPurchase(_:)",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/logSession()",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showEmbedView()",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/showSurvey(_:)"
            ],
            "title" : "Instance Methods"
          },
          {
            "anchor" : "Type-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/init()"
            ],
            "title" : "Type Methods"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/com.polling.polling\/objc(cs)NSObject"
            ],
            "kind" : "relationships",
            "title" : "Inherits From",
            "type" : "inheritsFrom"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@interface"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "POLPolling"
                },
                {
                  "kind" : "text",
                  "text" : " : "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSObject",
                  "text" : "NSObject"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/title",
        "value" : "POLReward"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Reward\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLReward"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/title",
        "value" : "POLSurvey"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1Survey\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLSurvey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/title",
        "value" : "POLViewType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1ViewType-swift.enum\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLViewType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1apiKey\/title",
        "value" : "apiKey"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1apiKey\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "apiKey"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1customerID\/title",
        "value" : "customerID"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1customerID\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "customerID"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1delegate\/title",
        "value" : "delegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1delegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "delegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1disableCheckingForAvailableSurveys\/title",
        "value" : "disableCheckingForAvailableSurveys"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1disableCheckingForAvailableSurveys\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "disableCheckingForAvailableSurveys"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1init()\/title",
        "value" : "polling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1init()\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "+ "
          },
          {
            "kind" : "identifier",
            "text" : "polling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logEvent(_:value:)\/title",
        "value" : "logEvent:value:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logEvent(_:value:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "logEvent:value:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logPurchase(_:)\/title",
        "value" : "logPurchase:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logPurchase(_:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "logPurchase:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logSession()\/title",
        "value" : "logSession"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1logSession()\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "logSession"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showEmbedView()\/title",
        "value" : "showEmbedView"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showEmbedView()\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "showEmbedView"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showSurvey(_:)\/title",
        "value" : "showSurvey:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1showSurvey(_:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "showSurvey:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1viewType-swift.property\/title",
        "value" : "viewType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1viewType-swift.property\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "viewType"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}