{
  "abstract" : [
    {
      "text" : "A protocol that defines methods the SDK can call to provide",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "information to your app",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.polling.polling\/documentation\/Polling"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:objc(pl)POLPollingDelegate",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "protocol"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "PollingDelegate"
      }
    ],
    "modules" : [
      {
        "name" : "Polling"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "PollingDelegate"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Protocol",
    "symbolKind" : "protocol",
    "title" : "PollingDelegate"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "protocol"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "PollingDelegate"
            },
            {
              "kind" : "text",
              "text" : " : "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(pl)NSObject",
              "text" : "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Implement these method to receive information from the Polling SDK.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        },
        {
          "inlineContent" : [
            {
              "text" : "After implementing these methods in an object, assign that object",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "to the delegate property of the shared singleton object accessed",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "through ",
              "type" : "text"
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
              "isActive" : true,
              "type" : "reference"
            },
            {
              "text" : "’s ",
              "type" : "text"
            },
            {
              "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/init()",
              "isActive" : true,
              "type" : "reference"
            },
            {
              "text" : " property. The SDK",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "calls the methods of your delegate at appropriate times.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.polling.polling\/objc(pl)NSObject"
      ],
      "kind" : "relationships",
      "title" : "Inherits From",
      "type" : "inheritsFrom"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "anchor" : "Instance-Methods",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(on:)",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onFailure:)",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onSuccess:)",
        "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/pollingOnSurveyAvailable()"
      ],
      "title" : "Instance Methods"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/polling\/pollingdelegate"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/polling\/pollingdelegate"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.polling.polling/documentation/Polling": {
  "abstract" : [
    {
      "text" : "Poll and survey your users with ease",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling": {
  "abstract" : [
    {
      "text" : "The primary SDK object",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Polling"
    }
  ],
  "role" : "symbol",
  "title" : "Polling",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling"
},
"doc://com.polling.polling/documentation/Polling/Polling/init()": {
  "abstract" : [
    {
      "text" : "Returns the ",
      "type" : "text"
    },
    {
      "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling",
      "isActive" : true,
      "type" : "reference"
    },
    {
      "text" : " singleton object.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "convenience"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/Polling\/init()",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "polling"
    }
  ],
  "role" : "symbol",
  "title" : "init()",
  "type" : "topic",
  "url" : "\/documentation\/polling\/polling\/init()"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate": {
  "abstract" : [
    {
      "text" : "A protocol that defines methods the SDK can call to provide",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "information to your app",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "PollingDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "PollingDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "PollingDelegate",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate/polling(on:)": {
  "abstract" : [
    {
      "text" : "Notifies your app when the user receives an award",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "polling"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "on"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLPolling",
      "text" : "Polling"
    },
    {
      "kind" : "text",
      "text" : "."
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)POLReward",
      "text" : "Reward"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(on:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "pollingOnReward:"
    }
  ],
  "required" : true,
  "role" : "symbol",
  "title" : "polling(on:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate\/polling(on:)"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate/polling(onFailure:)": {
  "abstract" : [
    {
      "text" : "Notifies your app when an error occurs",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "polling"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "onFailure"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onFailure:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "pollingOnFailure:"
    }
  ],
  "role" : "symbol",
  "title" : "polling(onFailure:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate\/polling(onfailure:)"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate/polling(onSuccess:)": {
  "abstract" : [
    {
      "text" : "Notifies your app when a survey is completed",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "polling"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "onSuccess"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onSuccess:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "pollingOnSuccess:"
    }
  ],
  "role" : "symbol",
  "title" : "polling(onSuccess:)",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate\/polling(onsuccess:)"
},
"doc://com.polling.polling/documentation/Polling/PollingDelegate/pollingOnSurveyAvailable()": {
  "abstract" : [
    {
      "text" : "Notifies your app when surveys are available",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "pollingOnSurveyAvailable"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/pollingOnSurveyAvailable()",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "pollingOnSurveyAvailable"
    }
  ],
  "required" : true,
  "role" : "symbol",
  "title" : "pollingOnSurveyAvailable()",
  "type" : "topic",
  "url" : "\/documentation\/polling\/pollingdelegate\/pollingonsurveyavailable()"
},
"doc://com.polling.polling/objc(pl)NSObject": {
  "identifier" : "doc:\/\/com.polling.polling\/objc(pl)NSObject",
  "title" : "NSObject",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Protocol"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "POLPollingDelegate"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "protocol"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Instance-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(on:)",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onFailure:)",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/polling(onSuccess:)",
              "doc:\/\/com.polling.polling\/documentation\/Polling\/PollingDelegate\/pollingOnSurveyAvailable()"
            ],
            "title" : "Instance Methods"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/com.polling.polling\/objc(pl)NSObject"
            ],
            "kind" : "relationships",
            "title" : "Inherits From",
            "type" : "inheritsFrom"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@protocol"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "POLPollingDelegate"
                },
                {
                  "kind" : "text",
                  "text" : " <"
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(pl)NSObject",
                  "text" : "NSObject"
                },
                {
                  "kind" : "text",
                  "text" : ">"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/title",
        "value" : "POLPolling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPolling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1init()\/title",
        "value" : "polling"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1Polling~1init()\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "+ "
          },
          {
            "kind" : "identifier",
            "text" : "polling"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/title",
        "value" : "POLPollingDelegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "POLPollingDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(on:)\/title",
        "value" : "pollingOnReward:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(on:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnReward:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(onFailure:)\/title",
        "value" : "pollingOnFailure:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(onFailure:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnFailure:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(onSuccess:)\/title",
        "value" : "pollingOnSuccess:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1polling(onSuccess:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnSuccess:"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1pollingOnSurveyAvailable()\/title",
        "value" : "pollingOnSurveyAvailable"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.polling.polling~1documentation~1Polling~1PollingDelegate~1pollingOnSurveyAvailable()\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "pollingOnSurveyAvailable"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}